name: projetogpsnovo
description: Aplicação Flutter para navegação na universidade.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.5
  webview_flutter: ^4.7.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  flutter_tts: ^4.2.2
  flutter_blue_plus: ^1.33.4
  permission_handler: ^12.0.0+1
  provider: ^6.1.1
  vibration: ^3.1.3
  speech_to_text: ^7.0.0
  shared_preferences: ^2.2.0
  audioplayers: ^6.5.0
  diacritic: ^0.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lang/
    - assets/images/home/logo_gps.png
    - assets/images/home/icon_camoes.png
    - assets/images/home/foto_camoes.png
    - assets/images/home/aluno.png
    - assets/images/map/00_piso.png
    - assets/images/map/-01_piso.png
    - assets/images/map/01_piso.png
    - assets/images/map/02_piso.png
    - assets/images/map/03_piso.png
    - assets/images/map/04_piso.png
    - assets/tts/navigation/nav_pt.json
    - assets/tts/navigation/nav_en.json
    - assets/tts/navigation/nav_de.json
    - assets/tts/navigation/nav_es.json
    - assets/tts/navigation/nav_fr.json
    - assets/tts/navigation/nav_it.json
    - assets/tts/navigation/nav_nl.json
    - assets/tts/navigation/nav_pl.json
    - assets/tts/navigation/nav_ru.json
    - assets/tts/navigation/nav_tr.json
    - assets/tts/tour/tour_pt.json
    - assets/tts/tour/tour_en.json
    - assets/tts/tour/tour_de.json
    - assets/tts/tour/tour_es.json
    - assets/tts/tour/tour_fr.json
    - assets/tts/tour/tour_it.json
    - assets/tts/tour/tour_nl.json
    - assets/tts/tour/tour_pl.json
    - assets/tts/tour/tour_ru.json
    - assets/tts/tour/tour_tr.json
    - assets/sounds/start_recording_sound.mp3
    - assets/sounds/stop_recording_sound.mp3
