name: projetogpsnovo
description: Aplicação Flutter para navegação na universidade.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.5
  webview_flutter: ^4.7.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  flutter_tts: ^4.2.2
  flutter_blue_plus: ^1.33.4
  permission_handler: ^12.0.0+1
  provider: ^6.1.1
  vibration: ^3.1.3
  speech_to_text: ^7.0.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lang/
    - assets/images/home/logo_gps.png
    - assets/images/home/icon_camoes.png
    - assets/images/home/foto_camoes.png
    - assets/images/home/aluno.png
    - assets/images/map/00_piso.png
    - assets/images/map/-01_piso.png
    - assets/images/map/-01_piso.png
    - assets/images/map/01_piso.png
    - assets/images/map/02_piso.png
    

 
